### ISSUE TITLE
reference links are broken. documentation link missing.

### ISSUE THREAD

**Issue by oronno** [greenrobot/essentials#20]
Most of the link in README.md section is broken. Like: [stream-based IO](https://github.com/greenrobot/essentials/blob/master/java-common/src/main/java/de/greenrobot/common/io/IoUtils.java)

Your website says: 

> For more details, please have a look at the documentation.

But I can't find a visible documentation link anywhere.

**Comment by greenrobot-team** [comment]
Thanks for reporting!
