### ISSUE TITLE
Issues when building with proguard (3.0.0-RC1)

### ISSUE THREAD

**Issue by mhiew** [greenrobot/essentials#23]
Building with proguard enabled would result in this error:
`PrimitiveArrayUtils$UnsafeImpl: can't find referenced class sun.misc.Unsafe`

adding the follow to my proguard configs seemed to help:
`-dontwarn sun.misc.Unsafe`

**Comment by greenrobot-team** [comment]
So this is an issue with your ProGuard configuration and not this library. Closing then. -ut
